### ISSUE TITLE
Сползание кружков возле фигур в геогебре.

### ISSUE THREAD

**Issue by VedMark** [MikhailSadovsky/geometry.drawings#29]
![_024](https://cloud.githubusercontent.com/assets/15463201/20788665/c66f6fac-b7c2-11e6-9dbb-7c899ce9a6b7.png)

**Comment by nastassiadanilova** [comment]
https://github.com/MikhailSadovsky/geometry.drawings/pull/42

**Comment by MikhailSadovsky** [comment]
Done
