### ISSUE TITLE
Убрать вычисление и трансляцию в базу знаний значения длины окружности

### ISSUE THREAD

**Issue by MikhailSadovsky** [MikhailSadovsky/geometry.drawings#36]
1) Убрать вычисление и трансляцию в базу знаний значения длины окружности. При этом узел длины окружности должен быть создан. Его величины и значения быть не должно
2) Проверить

Срок: до 4 декабря

**Comment by MikhailSadovsky** [comment]
![default](https://cloud.githubusercontent.com/assets/8840551/20858096/6da7a790-b94d-11e6-8a5b-7694b264681d.png)
Должен остаться узел длины окружности под отношением длина*. Узел должен быть включен в множество величин

**Comment by nastassiadanilova** [comment]
#42

**Comment by MikhailSadovsky** [comment]
Done
